language: python
sudo: false
python:
- '3.6'
- '3.5'
- '3.4'
- '2.7'
- pypy
env:
- MARSHMALLOW_VERSION="==2.0.0"
- MARSHMALLOW_VERSION=""
install:
- travis_retry pip install -U -r dev-requirements.txt
- travis_retry pip install -U .
- travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION" --pre
before_script:
- flake8 .
script: pytest
jobs:
  include:
  - stage: PyPI Release
    if: tag IS present
    python: '3.6'
    env: []
    before_install: true
    install: true
    script: echo "Releasing to PyPI..."
    after_success: true
    deploy:
      provider: pypi
      user: sloria
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: J05JjU6cY5RVHalwpCswhtGocSp3rcdVmUs1Z1FFRqBy18beTziRo1996OrqXqexXdFTQkW+RN2seirJDZhY2eB2WHp+2DN+cx2ynvu/VVGUq1L1WzylImOZptoUo+s5NEkM6R5AjEaJbOiLxMP3iYEiNPlRznw0V9NDOxX/xOg=
