language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  # Lowest supported version
  - MARSHMALLOW_VERSION="==1.2.0"
  # Latest release
  - MARSHMALLOW_VERSION=""

install:
  - travis_retry pip install -U -r dev-requirements.txt
  - travis_retry pip install -U .
  - travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION" --pre
  - travis_retry pip install -U git+https://github.com/marshmallow-code/marshmallow@dev
  - travis_retry pip install -U git+https://github.com/marshmallow-code/marshmallow-sqlalchemy@dev
before_script:
  - flake8 .
script:  py.test
