language: python
sudo: false
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

env:
  # Lowest supported version
  - MARSHMALLOW_VERSION="==2.0.0"
  # Latest release
  - MARSHMALLOW_VERSION=""

install:
  - travis_retry pip install -U -r dev-requirements.txt
  - travis_retry pip install -U .
  - travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION" --pre
before_script:
  - flake8 .
script:  py.test
